### ISSUE TITLE
Dual-coin profitability is using wrong hashrate

### ISSUE THREAD

**Issue by TrAnn3l** [autominer/autominer#1]
When using dual-coin profitability, autominer seems to using the full hashrate for the second algo. But when running, the GPU does not have this hashrate.
This causes that the worng algo is chosen, because autominer thinks, dual-coin is the most profitable, while it is the least profitable.

**Comment by autominer** [comment]
@TrAnn3l Thank you for bringing this to my attention. On my rigs, dual mining is always more profitable, but I guess this isn't always the case as you've demonstrated.  I plan to add a feature to allow scaling of hashrates for dual-mined coins to more accurately reflect your hashrates. Something along the lines of:

```yaml
ETH+LBC:
  command: "mine_eth_lbc.bat"
  LBC_scale: 0.0625 # When dualmining ETH+LBC, LBC runs at 6.25% of the hashrate in the WhatToMine config
```

I'll keep you posted!
